### ISSUE TITLE
doom-filesystem-tools

### ISSUE THREAD

**Issue by by-freon** [majomix/doom-filesystem-tools#1]
Ahoj
Jak má prosím tě fungovat ten prográmek na soubory  doom 2016?
Umí to upravit i soubory s příponou index.verify  a resources.verify?

Po zkompilování se mi vytvoří exe, ale po spuštění se nic nestane.
Visual studio mi žádnou chybu nehlásí. Třeba ue4-localization-tools-master po zkompilování funguje, ostatní tvé utility ne.
Díky za odpověď
freon

**Comment by majomix** [comment]
Ahoj, súbory .verify som neskúmal, a keďže som sa k prekladu nikdy nedostal, tak som to ani nepotreboval. Pokiaľ viem, netreba ich meniť, len nebudú fungovať achievementy, lebo sa hra prepne do developerského režimu. Ak o nich niekde nájdeš informácie, rád to doimplementujem.

Všetky programy sa spúšťajú pomocou príkazov. Editor na UE4 má možnosť spustenia buď s príkazmi, alebo cez GUI. Ostatné programy majú GUI iba ako indikáciu progresu.

Stačí niečo takéto:

`DoomFileSystemTools.exe -export -index="cesta\ku\gameresources.index" -dir="vystupny\priecinok"`

`DoomFileSystemTools.exe -import -index="cesta\ku\gameresources.index" -dir="vstupny\priecinok"`

Programy sú robené pre vlastné použitie, preto nemajú dokumentáciu :).

**Comment by by-freon** [comment]
Rozumím, díky za informace. To mi stačí.
